---
version: v1.0.0
server:
  port: 8080
  health_check_port: 80
  health_check_path: /healthz
  timeout: 10s
  shutdown_duration: 5s
  tls:
    enabled: true
    cert_key: cert
    key_key: key
    ca_key: ca
ntoken:
  athenz_domain:  _athenz_domain_
  service_name: _service_name_
  ntoken_path: ""
  private_key_env_name: athenz_private_key
  validate_token: false
  refresh_duration: 30m
  key_version: v1.0
  expiration: 20m
access_token:
  enable: true
  auth_header_key: Athenz-Principal
  athenz_url: https://www.athenz.com:4443/zts/v1
  expiration: "30m"
  proxy_principal: ""
roletoken:
  auth_header_key: Athenz-Principal
  athenz_url: https://www.athenz.com:4443/zts/v1
  expiration: 30m
  proxy_principal: ""
proxy:
  auth_header_key: Athenz-Principal
  role_header_key: Athenz-Role-Auth
  buffer_size: 1024
service_cert:
  enable: true
  athenz_url: https://www.athenz.com:4443/zts/v1
  athenz_root_ca: /etc/ssl/cert.pem
  dns_suffix: athenz.cloud
  refresh_duration: 30m
  expire_margin: 30h
  expiration: 720h
  intermediate_cert: true
  auth_header_key: Athenz-Principal
  spiffe: false
  subject:
    country: US
    province: California
    organization: "Oath Inc."
    organizational_unit: Athenz
